import type { FetchResult, Middleware, RequestContext } from "./types";
const replaceHeaders = (context: RequestContext, mutate: (headers: Headers) => void): RequestContext => { const headers = new Headers(context.request.headers); mutate(headers); return Object.freeze({ ...context, request: new Request(context.request, { headers }) }); };
export const bearerAuth = ({ token }: { token: string | (() => string | Promise<string>) }): Middleware => async (context, next) => { const resolved = typeof token === "function" ? await token() : token; return next(replaceHeaders(context, (headers) => headers.set("authorization", `Bearer ${resolved}`))); };
export function apiKeyAuth({ key, value, in: location = "header" }: { key: string; value: string | (() => string | Promise<string>); in?: "header" | "query" }): Middleware { return async (context, next) => { const resolved = typeof value === "function" ? await value() : value; if (location === "header") return next(replaceHeaders(context, (h) => h.set(key, resolved))); const url = new URL(context.request.url); url.searchParams.set(key, resolved); return next(Object.freeze({ ...context, request: new Request(url, context.request) })); }; }
export interface RetryOptions { attempts?: number; methods?: readonly string[]; statuses?: readonly number[]; delay?: (attempt: number) => number }
export function retry(options: RetryOptions = {}): Middleware { const attempts = options.attempts ?? 3; const methods = options.methods ?? ["GET", "HEAD", "PUT", "DELETE", "OPTIONS"]; const statuses = options.statuses ?? [408, 425, 429, 500, 502, 503, 504]; return async (context, next) => { if (!methods.includes(context.request.method) || context.request.body) return next(context); let result: FetchResult = await next(context); for (let attempt = 2; attempt <= attempts && (!result.ok && (result.kind === "network" || result.kind === "http" && statuses.includes(result.status))); attempt++) { const retryAfter = "response" in result ? result.response?.headers.get("retry-after") : null; const wait = retryAfter ? (/^\d+$/.test(retryAfter) ? Number(retryAfter) * 1000 : Math.max(0, Date.parse(retryAfter) - Date.now())) : options.delay?.(attempt) ?? 100 * 2 ** (attempt - 2); if (context.deadline && Date.now() + wait >= context.deadline) break; await new Promise<void>((resolve, reject) => { const timer = setTimeout(resolve, wait); context.request.signal.addEventListener("abort", () => { clearTimeout(timer); reject(context.request.signal.reason); }, { once: true }); }); result = await next(Object.freeze({ ...context, attempt, request: context.request.clone() })); } return result; }; }
const redacted = (headers: Headers) => Object.fromEntries([...headers].map(([k, v]) => [k, /authorization|cookie/i.test(k) ? "[REDACTED]" : v]));
export function logging(logger: { log(event: Record<string, unknown>): void } = console): Middleware { return async (context, next) => { logger.log({ phase: "request", operationId: context.operationId, method: context.request.method, url: context.request.url, headers: redacted(context.request.headers), attempt: context.attempt }); const result = await next(context); logger.log({ phase: "response", operationId: context.operationId, kind: result.kind, status: result.status, attempt: context.attempt }); return result; }; }
export interface TelemetryHooks { start?(context: RequestContext): unknown; end?(span: unknown, result: FetchResult): void; error?(span: unknown, error: unknown): void }
export function telemetry(hooks: TelemetryHooks): Middleware { return async (context, next) => { const span = hooks.start?.(context); try { const result = await next(context); hooks.end?.(span, result); return result; } catch (error) { hooks.error?.(span, error); throw error; } }; }
